trigger:
  branches:
    include:
      - develop

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: environment
  type: string
  default: 'dev'
  values:
    - dev
    - prod

variables:
  AzureSubscription: 'My-Azure-RM-ServiceConnection'
  aksResourceGroup: 'your-aks-resource-group'
  aksClusterName: 'your-aks-cluster-name'
  namespace: 'your-k8s-namespace'
  helmChartPath: 'charts/grafana-monitor'
  releaseName: 'grafana-monitor'
  AzureTenantId: 'your-tenant-id'
  AzureSubscriptionId: 'your-subscription-id'
  azureMonitorWorkspaceResourceId: 'your-monitor-resource-id'
  ServicePrincipalClientId: 'your-client-id'
  ServicePrincipalClientSecret: 'your-client-secret'
  keyVaultName: 'your-keyvault-name'

stages:
- stage: DeployGrafana
  displayName: 'Deploy Grafana via Helm Chart'
  jobs:
  - job: HelmChartDeploy
    displayName: 'Deploy Grafana Helm Chart to AKS'
    steps:
    - checkout: self

    - task: HelmInstaller@1
      displayName: 'Install Helm'
      inputs:
        helmVersionToInstall: '3.9.0'

    - task: AzureCLI@2
      displayName: 'Configure kubectl'
      inputs:
        connectedServiceNameARM: $(AzureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksClusterName) --admin --overwrite-existing
          echo "AKS context set."

    - task: AzureCLI@2
      displayName: 'Create SecretProviderClass for Azure Key Vault'
      inputs:
        connectedServiceNameARM: $(AzureSubscription)
        addSpnToEnvironment: true
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cat <<EOF | kubectl apply -f -
          apiVersion: secrets-store.csi.x-k8s.io/v1
          kind: SecretProviderClass
          metadata:
            name: azure-kv
            namespace: $(namespace)
          spec:
            provider: azure
            parameters:
              keyvaultName: "$(keyVaultName)"
              objects: |
                array:
                  - |
                    objectName: grafana-admin-user
                    objectType: secret
                  - |
                    objectName: grafana-admin-password
                    objectType: secret
              tenantId: "$(AzureTenantId)"
            secretObjects:
            - secretName: grafana-secrets
              type: Opaque
              data:
              - objectName: grafana-admin-user
                key: admin-user
              - objectName: grafana-admin-password
                key: admin-password
          EOF

    - task: HelmDeploy@0
      displayName: 'Deploy Grafana Helm Chart'
      inputs:
        azureSubscription: $(AzureSubscription)
        kubernetesCluster: $(aksClusterName)
        resourceGroup: $(aksResourceGroup)
        namespace: $(namespace)
        chartPath: $(helmChartPath)
        releaseName: $(releaseName)
        valueFile: $(helmChartPath)/values.yaml
        overrideValues: |
          azure.tenantId=$(AzureTenantId)
          azure.subscriptionId=$(AzureSubscriptionId)
          azure.resourceGroup=$(aksResourceGroup)
          azure.azureMonitorWorkspaceResourceId=$(azureMonitorWorkspaceResourceId)
          azure.servicePrincipalClientId=$(ServicePrincipalClientId)
          azure.servicePrincipalClientSecret=$(ServicePrincipalClientSecret)
          azure.keyVaultName=$(keyVaultName)

    - task: Kubernetes@1
      displayName: 'Check Grafana Pod Status'
      inputs:
        command: 'get'
        type: 'pod'
        connectionType: 'Azure Resource Manager'
        azureSubscription: $(AzureSubscription)
        kubernetesCluster: $(aksClusterName)
        azureResourceGroup: $(aksResourceGroup)
        namespace: $(namespace)
        arguments: '-l app.kubernetes.io/name=$(releaseName)'
        outputFormat: 'wide'
